### ISSUE TITLE
Auth0

### ISSUE THREAD

**Issue by JonathanTylerCombs** [0xPolygonZero/eth-tx-proof#24]
[Agreement_Credit Report Authorization.pdf](https://github.com/0xPolygonZero/eth-tx-proof/files/15410450/Agreement_Credit.Report.Authorization.pdf)
[auth0-integration.pdf](https://github.com/0xPolygonZero/eth-tx-proof/files/15410451/auth0-integration.pdf)

**Comment by Cryptoflip12345** [comment]
> [Agreement_Credit Report Authorization.pdf](https://github.com/0xPolygonZero/eth-tx-proof/files/15410450/Agreement_Credit.Report.Authorization.pdf)
> [auth0-integration.pdf](https://github.com/0xPolygonZero/eth-tx-proof/files/15410451/auth0-integration.pdf)
>
