### ISSUE TITLE
error[E0635]: unknown feature `stdsimd`

### ISSUE THREAD

**Issue by drewmois** [0xPolygonZero/eth-tx-proof#9]
Receiving the error: error[E0635]: unknown feature `stdsimd' when trying to run:

env RUSTFLAGS='-C target-cpu=native' cargo build --release

error[E0635]: unknown feature `stdsimd`
  --> /Users/drew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.6/src/lib.rs:99:42
   |
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `ahash` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...

**Comment by Nashtare** [comment]
Hello! Thanks for this issue.
This has been temporarily solved on the dependencies by pinning the nightly toolchain, as is done here in #10.
Once `ahash` version is bumped to 0.8, this should run smoothly with latest nightly again!

**Comment by Nashtare** [comment]
Closing this as it should be addressed with the pinned nightly version. Please let us know if you encounter any other issues!
